services:
  - type: web
    name: arunaprinters-backend
    rootDir: server
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: NODE_ENV
        value: production

